ensimpl/modules/page/__init__.py
# -*- coding: utf-8 -*-

ensimpl/modules/page/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def index():
    """Default page.

    Returns:
        :class:`flask.Response`: The response object.

    """
    return render_template('page/index.html')


@page.route('/ping')
def ping():
    """A page to test if any pages are up and running.

    Returns:
        :class:`flask.Response`: The response object with just 'OK!!!!'.
    """
    return 'OK!!!!'


@page.route('/search')
def search():
    """A page to test if any pages are up and running.

    Returns:
        :class:`flask.Response`: The response object.
    """
    return render_template('page/search.html')


@page.route("/js/karyotype.js")
def karyotype_js():
    """Get the Karyotype Javascript file.

    Returns:
        :class:`flask.Response`: The response which is the karyotype.js.

    """
    headers = {'Content-Type': 'application/javascript'}
    return render_template('page/karyotype.js'), 200, headers


@page.route("/navigator")
def navigator():
    """Show the navigator page.

    Returns:
        :class:`flask.Response`: The response object.
    """
    return render_template('page/navigator.html')


@page.route("/external_ids")
def external_ids():
    """Show the converter page.

    Returns:
        :class:`flask.Response`: The response object.
    """
    return render_template('page/external_ids.html')


@page.route("/lookup")
def lookup():
    """Show the batch ID lookup page.

    Returns:
        :class:`flask.Response`: The response object.
    """
    return render_template('page/lookup.html')


@page.route("/history")
def history():
    """Show the history page.

    Returns:
        :class:`flask.Response`: The response object.
    """
    return render_template('page/history.html')


@page.route("/help")
def help():
    """Show the navigator page.

    Returns:
        :class:`flask.Response`: The response object.
    """
    return render_template('page/help.html')


@page.route("/js/ensimpl.js")
def ensimpl_js():
    """Get the Ensimpl Javascript file.

    Returns:
        :class:`flask.Response`: The response which is the Javascript file.
    """
    headers = {'Content-Type': 'application/javascript'}
    return render_template('page/ensimpl.js'), 200, headers

ensimpl/modules/page/templates/page/help.html
{% extends 'layouts/base.html' %}

{% block title %}ensimpl Help{% endblock %}

{% block head %}
{% endblock %}

{% block body %}

{% include 'page/nav.html' %}

    <div class="container-fluid">


    <h1>ensimpl Help</h1>
    <p class="lead">Basic help for ensimpl API.</p>


</div>

{% endblock %}

{% block javascript %}



{% endblock %}

ensimpl/modules/page/templates/page/index.html
{% extends 'layouts/base.html' %}

{% block title %}ensimpl{% endblock %}

{% block head %}
<link rel="stylesheet"
      href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

<link rel="stylesheet"
      href="//cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
{% endblock %}

{% block body %}

{% include 'page/nav.html' %}

<div class="container-fluid">

    <h1>ensimpl</h1>
    <p class="lead">The ensimpl API was built by <a href="//churchill-lab.jax.org">The Churchill Lab</a> to simplify annotating various data from <a href="//www.ensembl.org">Ensembl</a>.</p>

</div>

{% endblock %}

{% block javascript %}

{% endblock %}

ensimpl/modules/page/templates/page/nav.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('page.index', _external=False) }}">ensimpl</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <!-- ml-auto will push all links to RIGHT //-->
      <!-- mr-auto will push all links to LEFT //-->
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
              <a href="{{ url_for('page.search', _external=False) }}" class="pl-5"><i class="fab fa-searchengin"></i> Search</a>
          </li>
          <li class="nav-item">
              <a href="{{ url_for('page.navigator', _external=False) }}" class="pl-5"><i class="far fa-compass"></i> Navigator</a>
          </li>
          <li class="nav-item">
              <a href="{{ url_for('page.lookup', _external=False) }}" class="pl-5"><i class="far fa-list-alt"></i> Lookup</a>
          </li>
          <li class="nav-item">
              <a href="{{ url_for('page.external_ids', _external=False) }}" class="pl-5"><i class="fas fa-exchange-alt"></i> External IDs</a>
          </li>
          <li class="nav-item">
              <a href="{{ url_for('page.history', _external=False) }}" class="pl-5"><i class="fas fa-landmark"></i> History</a>
          </li>
          <li class="nav-item">
              <a href="{{ url_for('page.help', _external=False) }}" class="pl-5"><i class="fas fa-question-circle"></i> Help</a>
          </li>
      </ul>
  </div>
</nav>